[build]
  base = "frontend"
  command = "npm ci --include=dev && npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/index.html"
  status = 200
